[[gperftools]]
arch = "aarch64"
git-tree-sha1 = "f97d05d5b1f3e096fd3c36569be58e1722d99c5b"
os = "macos"

    [[gperftools.download]]
    sha256 = "7b627e784f6e318ffaee830d1839b0c62755c78349202ddbffaec5ae80c690a5"
    url = "https://github.com/JuliaBinaryWrappers/gperftools_jll.jl/releases/download/gperftools-v2.9.1+0/gperftools.v2.9.1.aarch64-apple-darwin.tar.gz"
[[gperftools]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dcd1dac0a9f8a9258fa6a0cef8d9df7e6871697a"
libc = "glibc"
os = "linux"

    [[gperftools.download]]
    sha256 = "dc57fd2969bc121a6fe409553870ca1add4acaaee4902716017a7555e4e40dbc"
    url = "https://github.com/JuliaBinaryWrappers/gperftools_jll.jl/releases/download/gperftools-v2.9.1+0/gperftools.v2.9.1.aarch64-linux-gnu-cxx03.tar.gz"
[[gperftools]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1243ef912b5ec0ede94a26735cd88b7cd62baab9"
libc = "glibc"
os = "linux"

    [[gperftools.download]]
    sha256 = "75713a223ca019347dac2f56e1f5d34e8ec548586c498cffd4676d0fbacff23b"
    url = "https://github.com/JuliaBinaryWrappers/gperftools_jll.jl/releases/download/gperftools-v2.9.1+0/gperftools.v2.9.1.aarch64-linux-gnu-cxx11.tar.gz"
[[gperftools]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ee1e63646a7ba3144a06e9145cdaf8985835be09"
libc = "glibc"
os = "linux"

    [[gperftools.download]]
    sha256 = "d309b00b369320c857ad2a56a75be836510e95da404fd4fab4917c7bb53ed094"
    url = "https://github.com/JuliaBinaryWrappers/gperftools_jll.jl/releases/download/gperftools-v2.9.1+0/gperftools.v2.9.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[gperftools]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3781a8b237c7fc94c34cc3cd68f7414731058271"
libc = "glibc"
os = "linux"

    [[gperftools.download]]
    sha256 = "5747b58a58f742f1168348481eea255f6e36f3ae49ea65c2b066bb6991dca481"
    url = "https://github.com/JuliaBinaryWrappers/gperftools_jll.jl/releases/download/gperftools-v2.9.1+0/gperftools.v2.9.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[gperftools]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cab4fce9ea6314e623d0629085247c6d41355c36"
libc = "musl"
os = "linux"

    [[gperftools.download]]
    sha256 = "40ac7f6c10e5276e0add350b87f9311dd2b4b0f4bdcc73b1fcebfee8a58deff5"
    url = "https://github.com/JuliaBinaryWrappers/gperftools_jll.jl/releases/download/gperftools-v2.9.1+0/gperftools.v2.9.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[gperftools]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f6e148b4efaaacc9cc3be829bc3744e7a2d6e10a"
libc = "musl"
os = "linux"

    [[gperftools.download]]
    sha256 = "3af8cf7afb8b674ba453a50a5288f1d03572df122bb0d224768d61526f5ae33b"
    url = "https://github.com/JuliaBinaryWrappers/gperftools_jll.jl/releases/download/gperftools-v2.9.1+0/gperftools.v2.9.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[gperftools]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f05be943276093bff5364482d2aa1e92aba7f5f9"
libc = "glibc"
os = "linux"

    [[gperftools.download]]
    sha256 = "2005c596d8b5dc2bb4f744ec08b52ab6a8f6464210883d4fbc59d4b23513a912"
    url = "https://github.com/JuliaBinaryWrappers/gperftools_jll.jl/releases/download/gperftools-v2.9.1+0/gperftools.v2.9.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[gperftools]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "51c10a97bd927d3459d8aa3d356e80766d6bbfbc"
libc = "glibc"
os = "linux"

    [[gperftools.download]]
    sha256 = "c7d5a69c460ebed94a796ece7da30eb3c1b0711158eeaadbafdaac3a55350acc"
    url = "https://github.com/JuliaBinaryWrappers/gperftools_jll.jl/releases/download/gperftools-v2.9.1+0/gperftools.v2.9.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[gperftools]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "80a4c7db4414d133c32b7aa26765af7d88df37cd"
libc = "musl"
os = "linux"

    [[gperftools.download]]
    sha256 = "3f02dbd44a3c4bb9604fe21db668d7c1117ffdfe492ea4988fa6991661186091"
    url = "https://github.com/JuliaBinaryWrappers/gperftools_jll.jl/releases/download/gperftools-v2.9.1+0/gperftools.v2.9.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[gperftools]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "051d2dea8bb620d274f442be4f24c2562cea6e1b"
libc = "musl"
os = "linux"

    [[gperftools.download]]
    sha256 = "113a4d74c891001d4b24d1577651167545e79f1083deefdc29f9fbff0cc1d92f"
    url = "https://github.com/JuliaBinaryWrappers/gperftools_jll.jl/releases/download/gperftools-v2.9.1+0/gperftools.v2.9.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[gperftools]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2f1f77d5b85505bcc67feed6492084d199c8d2f6"
libc = "glibc"
os = "linux"

    [[gperftools.download]]
    sha256 = "8916e0203c78cab477ab631085467fcadb6d15b3f0db83003180121e48651d5a"
    url = "https://github.com/JuliaBinaryWrappers/gperftools_jll.jl/releases/download/gperftools-v2.9.1+0/gperftools.v2.9.1.i686-linux-gnu-cxx03.tar.gz"
[[gperftools]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bad691d7f7b038a0dc02b35306f1ef25265396be"
libc = "glibc"
os = "linux"

    [[gperftools.download]]
    sha256 = "5019f2342bcd0eed6d318d7b76cb5ee300630d11362f1e3be4e8c8d5392db861"
    url = "https://github.com/JuliaBinaryWrappers/gperftools_jll.jl/releases/download/gperftools-v2.9.1+0/gperftools.v2.9.1.i686-linux-gnu-cxx11.tar.gz"
[[gperftools]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "addcf45778f15d9a70fe47bf808361fb230aa395"
libc = "musl"
os = "linux"

    [[gperftools.download]]
    sha256 = "3203c3328618763f57fec8475f3a8021ed899b87f6648db571789049515fbf46"
    url = "https://github.com/JuliaBinaryWrappers/gperftools_jll.jl/releases/download/gperftools-v2.9.1+0/gperftools.v2.9.1.i686-linux-musl-cxx03.tar.gz"
[[gperftools]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b2b37cedfef9edf2a5fed95239224aa9ffc76710"
libc = "musl"
os = "linux"

    [[gperftools.download]]
    sha256 = "4387f539a1e26401d937feb976010f373b6ee56d259508777055ad7661d5cb36"
    url = "https://github.com/JuliaBinaryWrappers/gperftools_jll.jl/releases/download/gperftools-v2.9.1+0/gperftools.v2.9.1.i686-linux-musl-cxx11.tar.gz"
[[gperftools]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dcdbd4ffc19664f23fd50867f3d7133c6f99064f"
libc = "glibc"
os = "linux"

    [[gperftools.download]]
    sha256 = "0a6d508f0339ccad10504dac233ce76e6e1ef4f469a545d6c29178d7bfb95a61"
    url = "https://github.com/JuliaBinaryWrappers/gperftools_jll.jl/releases/download/gperftools-v2.9.1+0/gperftools.v2.9.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[gperftools]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f26ab8a7a2a08c3bba12386cc5501ff5ee46088"
libc = "glibc"
os = "linux"

    [[gperftools.download]]
    sha256 = "385859eb986ae5d42d20812cfe21e95681537cf56e99cdb2cee25e71c72655bb"
    url = "https://github.com/JuliaBinaryWrappers/gperftools_jll.jl/releases/download/gperftools-v2.9.1+0/gperftools.v2.9.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[gperftools]]
arch = "x86_64"
git-tree-sha1 = "53044638e9c0cd58407ce4d23fc141bd1477a600"
os = "macos"

    [[gperftools.download]]
    sha256 = "ded17efc4c0e5f2da642e72feea857eb4fd7fbf363b2cf4234ba538db58ad3d1"
    url = "https://github.com/JuliaBinaryWrappers/gperftools_jll.jl/releases/download/gperftools-v2.9.1+0/gperftools.v2.9.1.x86_64-apple-darwin.tar.gz"
[[gperftools]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8a46f85ff56bd7f8c9f454ca7959ce1938f7ad8e"
libc = "glibc"
os = "linux"

    [[gperftools.download]]
    sha256 = "922c9a98c244baa0c0183587eb2c169324816691354c88805937f21125a2ed52"
    url = "https://github.com/JuliaBinaryWrappers/gperftools_jll.jl/releases/download/gperftools-v2.9.1+0/gperftools.v2.9.1.x86_64-linux-gnu-cxx03.tar.gz"
[[gperftools]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef5796597117b6e5ccaf0c7e8fe452252a8ab677"
libc = "glibc"
os = "linux"

    [[gperftools.download]]
    sha256 = "91372d70ca6dcc0a96dc347fd8f50770b37ea86246d053b524fa4a761de95d95"
    url = "https://github.com/JuliaBinaryWrappers/gperftools_jll.jl/releases/download/gperftools-v2.9.1+0/gperftools.v2.9.1.x86_64-linux-gnu-cxx11.tar.gz"
[[gperftools]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1b481839f02a9515749d4598228b920a08c90b60"
libc = "musl"
os = "linux"

    [[gperftools.download]]
    sha256 = "c337a304b1f3e8ff330d5880d05d224cd6867f7eee35e866a8003a2d01c9075f"
    url = "https://github.com/JuliaBinaryWrappers/gperftools_jll.jl/releases/download/gperftools-v2.9.1+0/gperftools.v2.9.1.x86_64-linux-musl-cxx03.tar.gz"
[[gperftools]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c0876fc2e27cfca0473d44c1af19b8a040b46e4"
libc = "musl"
os = "linux"

    [[gperftools.download]]
    sha256 = "d5c0137b4a83604f0cdb7d79fa7866cad8d5a68cbe0e659a6a6564f68d85432b"
    url = "https://github.com/JuliaBinaryWrappers/gperftools_jll.jl/releases/download/gperftools-v2.9.1+0/gperftools.v2.9.1.x86_64-linux-musl-cxx11.tar.gz"
[[gperftools]]
arch = "x86_64"
git-tree-sha1 = "28ffe188b08563ecee8a38fa50811546a795b78c"
os = "freebsd"

    [[gperftools.download]]
    sha256 = "8e979ad6fe21e43c69f72eec6932f7c1b02042f5070a22d3046199d21a84a81e"
    url = "https://github.com/JuliaBinaryWrappers/gperftools_jll.jl/releases/download/gperftools-v2.9.1+0/gperftools.v2.9.1.x86_64-unknown-freebsd.tar.gz"
