# Autogenerated wrapper script for gperftools_jll for aarch64-apple-darwin
export libprofiler, libtcmalloc, libtcmalloc_and_profiler, libtcmalloc_debug, libtcmalloc_minimal, libtcmalloc_minimal_debug

using LibUnwind_jll
JLLWrappers.@generate_wrapper_header("gperftools")
JLLWrappers.@declare_library_product(libprofiler, "@rpath/libprofiler.0.dylib")
JLLWrappers.@declare_library_product(libtcmalloc, "@rpath/libtcmalloc.4.dylib")
JLLWrappers.@declare_library_product(libtcmalloc_and_profiler, "@rpath/libtcmalloc_and_profiler.4.dylib")
JLLWrappers.@declare_library_product(libtcmalloc_debug, "@rpath/libtcmalloc_debug.4.dylib")
JLLWrappers.@declare_library_product(libtcmalloc_minimal, "@rpath/libtcmalloc_minimal.4.dylib")
JLLWrappers.@declare_library_product(libtcmalloc_minimal_debug, "@rpath/libtcmalloc_minimal_debug.4.dylib")
function __init__()
    JLLWrappers.@generate_init_header(LibUnwind_jll)
    JLLWrappers.@init_library_product(
        libprofiler,
        "lib/libprofiler.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libtcmalloc,
        "lib/libtcmalloc.4.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libtcmalloc_and_profiler,
        "lib/libtcmalloc_and_profiler.4.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libtcmalloc_debug,
        "lib/libtcmalloc_debug.4.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libtcmalloc_minimal,
        "lib/libtcmalloc_minimal.4.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libtcmalloc_minimal_debug,
        "lib/libtcmalloc_minimal_debug.4.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
