# Autogenerated wrapper script for gperftools_jll for armv6l-linux-gnueabihf-cxx11
export libprofiler, libtcmalloc, libtcmalloc_and_profiler, libtcmalloc_debug, libtcmalloc_minimal, libtcmalloc_minimal_debug

using LibUnwind_jll
JLLWrappers.@generate_wrapper_header("gperftools")
JLLWrappers.@declare_library_product(libprofiler, "libprofiler.so.0")
JLLWrappers.@declare_library_product(libtcmalloc, "libtcmalloc.so.4")
JLLWrappers.@declare_library_product(libtcmalloc_and_profiler, "libtcmalloc_and_profiler.so.4")
JLLWrappers.@declare_library_product(libtcmalloc_debug, "libtcmalloc_debug.so.4")
JLLWrappers.@declare_library_product(libtcmalloc_minimal, "libtcmalloc_minimal.so.4")
JLLWrappers.@declare_library_product(libtcmalloc_minimal_debug, "libtcmalloc_minimal_debug.so.4")
function __init__()
    JLLWrappers.@generate_init_header(LibUnwind_jll)
    JLLWrappers.@init_library_product(
        libprofiler,
        "lib/libprofiler.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libtcmalloc,
        "lib/libtcmalloc.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libtcmalloc_and_profiler,
        "lib/libtcmalloc_and_profiler.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libtcmalloc_debug,
        "lib/libtcmalloc_debug.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libtcmalloc_minimal,
        "lib/libtcmalloc_minimal.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libtcmalloc_minimal_debug,
        "lib/libtcmalloc_minimal_debug.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
